### ISSUE TITLE
워프 삭제 후 포탈파티클/블럭포탈을 이용해 워프 시도 시 오류

### ISSUE THREAD

**Issue by nnnlog** [SOLOPlugins-PocketMine/SPortal#2]
![photo_2017-08-19_08-48-04](https://user-images.githubusercontent.com/20399222/29481346-2735c9a6-84bb-11e7-8d00-c83a3c77b680.jpg)
![photo_2017-08-19_08-48-06](https://user-images.githubusercontent.com/20399222/29481347-27390ada-84bb-11e7-8853-c34872dfed9c.jpg)

워프 삭제 시 포탈 파티클이나 블럭 포탈도 함께 제거되는 기능이 있으면 좋을 것 같습니다.

**Comment by solo5star** [comment]
에러 리포트 감사합니다. 말씀해주신 의견도 참고하도록 할께요

**Comment by nnnlog** [comment]
#1 이건 확인하셨나요..?

**Comment by nnnlog** [comment]
솔로님, 혹시 IDE 뭐 쓰시는지 알 수 있을까요?

**Comment by solo5star** [comment]
@nnnlog Atom 사용합니다
atom.io
